/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/（AI葵）cuda教学': RouteRecordInfo<'/posts/（AI葵）cuda教学', '/posts/（AI葵）cuda教学', Record<never, never>, Record<never, never>>,
    '/posts/3dgs/[AI葵]3DGS cuda讲解': RouteRecordInfo<'/posts/3dgs/[AI葵]3DGS cuda讲解', '/posts/3dgs/:AI葵()3DGS cuda讲解', { AI葵: ParamValue<true> }, { AI葵: ParamValue<false> }>,
    '/posts/3dgs/3D Gaussian Splatting': RouteRecordInfo<'/posts/3dgs/3D Gaussian Splatting', '/posts/3dgs/3D Gaussian Splatting', Record<never, never>, Record<never, never>>,
    '/posts/分割论文复现记录': RouteRecordInfo<'/posts/分割论文复现记录', '/posts/分割论文复现记录', Record<never, never>, Record<never, never>>,
    '/posts/分割论文阅读整理': RouteRecordInfo<'/posts/分割论文阅读整理', '/posts/分割论文阅读整理', Record<never, never>, Record<never, never>>,
    '/posts/分割总结': RouteRecordInfo<'/posts/分割总结', '/posts/分割总结', Record<never, never>, Record<never, never>>,
    '/posts/论文阅读笔记': RouteRecordInfo<'/posts/论文阅读笔记', '/posts/论文阅读笔记', Record<never, never>, Record<never, never>>,
    '/posts/前端/面经': RouteRecordInfo<'/posts/前端/面经', '/posts/前端/面经', Record<never, never>, Record<never, never>>,
    '/posts/前端/前端知识简记': RouteRecordInfo<'/posts/前端/前端知识简记', '/posts/前端/前端知识简记', Record<never, never>, Record<never, never>>,
    '/posts/前端/日记': RouteRecordInfo<'/posts/前端/日记', '/posts/前端/日记', Record<never, never>, Record<never, never>>,
    '/posts/前端/周记': RouteRecordInfo<'/posts/前端/周记', '/posts/前端/周记', Record<never, never>, Record<never, never>>,
    '/posts/前端/周记（鹅）': RouteRecordInfo<'/posts/前端/周记（鹅）', '/posts/前端/周记（鹅）', Record<never, never>, Record<never, never>>,
    '/posts/前端/bilibili_danmaku_princess': RouteRecordInfo<'/posts/前端/bilibili_danmaku_princess', '/posts/前端/bilibili_danmaku_princess', Record<never, never>, Record<never, never>>,
    '/posts/实验记录': RouteRecordInfo<'/posts/实验记录', '/posts/实验记录', Record<never, never>, Record<never, never>>,
    '/posts/随笔/虚拟人前置知识': RouteRecordInfo<'/posts/随笔/虚拟人前置知识', '/posts/随笔/虚拟人前置知识', Record<never, never>, Record<never, never>>,
    '/posts/随笔/一些思路': RouteRecordInfo<'/posts/随笔/一些思路', '/posts/随笔/一些思路', Record<never, never>, Record<never, never>>,
    '/posts/随笔/LLM相关': RouteRecordInfo<'/posts/随笔/LLM相关', '/posts/随笔/LLM相关', Record<never, never>, Record<never, never>>,
    '/posts/cg/games101': RouteRecordInfo<'/posts/cg/games101', '/posts/cg/games101', Record<never, never>, Record<never, never>>,
    '/posts/cg/games103': RouteRecordInfo<'/posts/cg/games103', '/posts/cg/games103', Record<never, never>, Record<never, never>>,
    '/posts/cg/srp': RouteRecordInfo<'/posts/cg/srp', '/posts/cg/srp', Record<never, never>, Record<never, never>>,
    '/posts/cg/unity shader入门精要': RouteRecordInfo<'/posts/cg/unity shader入门精要', '/posts/cg/unity shader入门精要', Record<never, never>, Record<never, never>>,
    '/posts/nerf/AI葵/nerf程序码讲解': RouteRecordInfo<'/posts/nerf/AI葵/nerf程序码讲解', '/posts/nerf/AI葵/nerf程序码讲解', Record<never, never>, Record<never, never>>,
    '/posts/nerf/AI葵/nerf与它的快乐伙伴们': RouteRecordInfo<'/posts/nerf/AI葵/nerf与它的快乐伙伴们', '/posts/nerf/AI葵/nerf与它的快乐伙伴们', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
